---
version: 1.0
slug: AiO Flasher
name: AiO CC2652P7 ZIGBEE Flasher
description: Addon to flash the Zigbee Driver on the AiO Sensor
url: https://github.com/Xorfee/AiOZigbee
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
image: "ghcr.io/mercenaruss/{arch}-addon-zigstar-cc2652p7-flasher"
init: false
options:
  network_device: null
  coordinator_fw: false
  router_fw: false
  firmware_url: ""
  trigger_bsl: false
schema:
  network_device: str?
  coordinator_fw: bool
  router_fw: bool
  firmware_url: str?
stage: experimental
startup: once
boot: manual
